# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: publish artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish-artifact:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Publish
      run: dotnet publish -c Release
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: nsdc_artifact
        path: /home/runner/work/needlefish/needlefish/Needlefish.Compiler/bin/Release/net7.0/win-x64/publish/nsdc.exe
